"""initial migration

Revision ID: 9a1b002be2a9
Revises: 
Create Date: 2022-10-09 00:33:26.529872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1b002be2a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question_table', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('question_table', 'created_at',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_unique_constraint(None, 'question_table', ['question'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_table', type_='unique')
    op.alter_column('question_table', 'created_at',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('question_table', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=0, increment=1, minvalue=0, maxvalue=1000000, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
